### ISSUE TITLE
combat logic

### ISSUE THREAD

**Issue by allengx** [AllenGX/Design#2]
蓝量不足时技能施放失败，不执行操作-----------is Over

**Comment by allengx** [comment]
回合设置放在GameScene中-----------is Over

**Comment by allengx** [comment]
SkillUseStruct 只能执行战斗指令，不包括使用道具，这块需要修改。

class Order


class SkillUseStruct ：Order

class ProductUseStruct：Order
---------------is Over

**Comment by AllenGX** [comment]
人物站位设置

技能指定攻击范围

**Comment by allengx** [comment]
问题:
背包出现空指针，需要在遍历之前判断是否为空
问题定位  SetGoods()

--------------is Over

**Comment by allengx** [comment]
GameStart 对外暴露一些接口
完善注解

------------is Over

**Comment by AllenGX** [comment]
经验上限和计算公式

**Comment by AllenGX** [comment]
背景音乐

**Comment by AllenGX** [comment]
人物系统

**Comment by AllenGX** [comment]
存档读取

**Comment by allengx** [comment]
- [x] 1.UI战斗动画完整实现（攻击动画，受击动画，使用道具动画，伤害飙字，血条扣除，计时，战斗菜单栏）-------------（4-14之前）GHY
- [x] 2.技能、道具UI绑定--------------------（4-14之前）GHY
- [x] 3.脚本剧情---------------------------（4-21之前完成4-14提交初稿）GHY
- [x] 4.任务模块---------------------------（4-14开始动工，4-21完成）GX
- [x] 5.存档读取----------------------------（4-28之前）GX
- [x] 6.经验计算公式完善-----------------（4-14之前）GHY
- [ ] 7.背景音乐添加----------------------（4-21之前）GX
- [x] 8.人物战斗站位和选中目标之一的目标列表绑定，站位ID排序（敌人0~7）(玩家10~12)--------------------------（4-14之前）GX
- [x] 9.剧情对话-----------------------（4-28之前）GHY
- [ ] 10.数值测试和bug调试，画面完善，内容增添（技能，道具，装备。。。）----（5-4之前）GX，GHY

**Comment by wuaoao** [comment]
GameControl 类，GetInput方法 ，for(int j = 0; j <= playerIDAliveList.Count; j++) 去掉等于


------------------------------------isOver

**Comment by wuaoao** [comment]
Person类 加 两个参数，string 名字，string 战斗图片资源路径 要求外部可访问，构造方法里也需要这两个属性

------------------------------------------isOver

**Comment by wuaoao** [comment]
GameControl 类，GetInput方法 ，
public int GetInput(int skillID,int casterID,int targetID, ref float startTime)
    {
        Skill skill=gameSence.allDict[casterID].GetSkill(skillID);

应对道具方法

------------------------isOver

**Comment by wuaoao** [comment]
1.BackPack类 Refresh()方法
if (this.goods[i].GoodNumber <= 0)
            {
                this.goods[i] = null;
            }
空指针 改为
if (this.goods[i] != null && this.goods[i].GoodNumber <= 0)
            {
                this.goods[i] = null;
            }

2.Equipment类中，所有的头部装备 heads 拼错成 head 了 这边我改成heads

3.GameControl GetInput 方法
改为：
 Order order = null;
。。。。。
 else
        {
            //是道具
            targetIDList = new List<int> { };
            targetIDList.Add(targetID);
            order = new ProductUseStruct(casterID, objID, targetIDList);
        }

4.使用GetInput方法物品减少两个

--------------------------isOver

**Comment by allengx** [comment]
角色对象变为可选择主角色

**Comment by allengx** [comment]
- [x] 攻击动画每回合结束延时调高一些
- [x] 攻击动画调大一些
- [x] 飙字效果调大一些
- [x] 人物移动时阻力调大或者速度固定
- [x] 信息栏数值显示不能重叠
- [x] 战斗时战斗菜单放在场景右侧一字形而不是田字型
- [x] 场景外菜单栏太大，适当调小
- [x] 药品使用也需要添加跳字和延时
- [x] 人物血量设计，血量成长设计优化
- [x]  灼烧buff人物变红效果
- [x] 视情况在人物行走时添加音效
- [x] 敌人血量显示去除
- [x] 添加人物buff显示效果

**Comment by allengx** [comment]
战斗测评测试bug：
- [x] 怪物自己会突然给自己嗑药（突然播放嗑药动画）
- [x] 我方使用药品时，不论选中哪一种药品，默认都是用背包第一个药品
- [x] 没蓝施法时，有时候不会施法，有时候会施放一半（烈焰风暴三段有时候只有一段或两段）
- [x] 场景数据和人物信息不同步（血条数值改变应该在每个动画之后而不是一轮结束）
- [x] 大火球技能选中目标存在问题，选第一个打第二个（可能是动画播放的问题，目标对象在第二次技能释放时不会更新）
- [x] 人物被攻击后有时不会变红，可能目标参数传入有误
- [x] 群攻技能音效会创建多个
- [x] buff回合数到了不会清空

**Comment by allengx** [comment]
- [x] 三个主角背景故事
- [x] 数值设置

**Comment by allengx** [comment]
- [x] 怪物死亡后依旧在场，可以用迭代器让其透明度从255到0切换几次后消失（类似闪烁效果）
- [x] 血条扣血速度太慢，适当调快
- [x] 岩浆爆破技能还是1滴血，后续需要把调整好的数值写入代码。
- [x] 怪物死后，玩家依旧可以播放动画。
- [x] 关于对话框内字体问题，可以同length判断长度，在中间插入‘\n’。
- [x] 某个地图内可以遭遇怪物，可以在进入地图时，游戏正上方弹出一个提示框，几秒后小时之类的。具体实现你可以根据个人理解，总之需要有些许提示。。。
- [x] 下一场战斗开始时，上一场战斗的buff还会遗留。原因：每次战斗开始时，第一回合结束才会刷新buff状态，既上一场战斗结束后buff纵使在玩家的buff列表被清除，也只能在下一场战斗第一回合结束后更新。
- [x] 药品使用会让自己口血。。。（仅仅是血条显示上）
- [x] 使用药品报错修改gamecontrol 第400行代码
`int key=-1;
                if(order is SkillUseStruct)
                {
                    if (((SkillUseStruct)order).SkillID != 1011)
                    {
                        RefreshBuffTime(gameSence.allDict[order.CasterID]);
                    }
                }`

**Comment by allengx** [comment]
- [x] 回到标题
- [x] 人物走路音效
- [x] 任务提示信息栏
- [x] NPC名称、地图名称显示
- [x] 对话进入战斗添加提示框
- [x] 怪物死亡
从上至下优先级依次递减

**Comment by allengx** [comment]
- [x] 道具使用bug，选哪种道具默认都用第一种。
- [x] 怪物和人物buff挂不上问题（临危不惧、烈焰风暴）。
- [x] 战斗结束了人物技能一段依旧会施放（临危不惧），考虑把伤害为0的技能动画忽略试试。
- [x] NPC名字显示问题，出现空clone对象和缺少clone对象。
- [x] sname1、sname2、sname3替换成人名。
- [x] 存档读不到问题。
- [x] 劲敌数值问题，主角队一个技能直接被秒杀，对数值适当进行调整。
- [x] 退出游戏再次选档进入时，左上角场景名称依旧会保留。
- [x] 任务界面存在问题、获得任务物品不会更新显示。
- [x] 遇怪定时器出现长时间不遇怪情况，想办法随机遇怪或者超过某个时长直接遇怪。

**Comment by allengx** [comment]
- [x] 人物战败后画面逐渐变黑，10s后全黑，弹出提示框是否重新开始，是就回到开始界面、否直接关闭游戏
Application.Quit(); 
- [x] 野猪和黑野猪区分一下
- [x] 装备处的人物名称未修改
- [x] 人物死亡后输入指令出现空指针
- [ ] buff不同步问题（暂不修改）
- [ ] 大火球技能反向问题（暂不修改）
- [x] 技能击杀目标后无法给自己添加buff问题
- [ ] 解密关需要一些解密提示，另外人物文档给我详细的解密说明
- [x] 战斗有时候会出现提前结束问题
- [x] 回合结束后，直接回到场景（降低在战斗界面中的等待时间）
